mkcert_hostnames: "{{ lookup('env','BTCPAY_HOST') }} {{ lookup('env','WOOCOMMERCE_HOST') }} pi.hole"

mkcert_working_dir: /root/.local/share/mkcert

mkcert_rootca: "{{mkcert_working_dir}}/rootCA.pem"
mkcert_rootca_key: "{{mkcert_working_dir}}/rootCA-key.pem"
mkcert_certificate_file: "{{mkcert_working_dir}}/default.crt"
mkcert_certificate_key_file: "{{mkcert_working_dir}}/default.key"
mkcert_fullchain_file: "{{mkcert_working_dir}}/fullchain.pem"
