- name: Download golang backports key from ubuntu keyserver
  ansible.builtin.get_url:
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x876B22BA887CA91614B5323FC631127F87FA12D1"
    dest: "/usr/share/keyrings/simon-eisenmann-golang-backports.asc"

- name: Add golang backports repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/simon-eisenmann-golang-backports.asc] http://ppa.launchpad.net/longsleep/golang-backports/ubuntu bionic main"
    state: present

- name: apt-get update
  apt:
    update_cache: yes

- name: Install go
  apt:
    name: ['golang-{{versions.go}}-go']
    state: latest

- name: Symlink go versioned executable to /usr/bin/go
  file:
    src: "/usr/lib/go-{{versions.go}}/bin/go"
    dest: /usr/bin/go
    state: link

- name: Ensure GOPATH is set in bashrc
  lineinfile:
    path: "/root/.bashrc"
    line: 'export GOPATH=/root/go'
    create: yes

- name: Ensure GOPATH/bin is in user path
  lineinfile:
    path: "/root/.bashrc"
    line: 'export PATH=$PATH:$GOPATH/bin'
    create: yes
