username: "{{ 'pi' if ansible_architecture == 'aarch64' else 'debian' if ansible_architecture == 'x86_64' else 'undefined' }}"

paths:
  apps: /opt/apps
  backups: /opt/backups
  home: "/home/{{username}}"
  rpi_vault: /opt/rpi_vault
  sda3_luks_keyfile: /opt/rpi_vault/sda3_luks_keyfile
  wireguard_keyfile: /opt/rpi_vault/wireguard_keyfile

versions:
  electrum: 4.6.2
  electrum_checksum: sha256:66bc3301e78c36bb3a2b32c60e0e68045ec4f8618b60255cccee91d7c4ca46e1
  chantools: v0.9.2
  go: 1.13

# Network interfaces
interface_docker_bridge: br-btcpayserver
interfaces_host: "{{ (ansible_facts.interfaces | difference(ansible_facts.interfaces | map('regex_search', '^(lo|br-btcpayserver|docker|veth).*' )) | sort ) }}"
